/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateWaterAreaArgs } from "./CreateWaterAreaArgs";
import { UpdateWaterAreaArgs } from "./UpdateWaterAreaArgs";
import { DeleteWaterAreaArgs } from "./DeleteWaterAreaArgs";
import { WaterAreaCountArgs } from "./WaterAreaCountArgs";
import { WaterAreaFindManyArgs } from "./WaterAreaFindManyArgs";
import { WaterAreaFindUniqueArgs } from "./WaterAreaFindUniqueArgs";
import { WaterArea } from "./WaterArea";
import { WaterAreaService } from "../waterArea.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => WaterArea)
export class WaterAreaResolverBase {
  constructor(
    protected readonly service: WaterAreaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "WaterArea",
    action: "read",
    possession: "any",
  })
  async _waterAreasMeta(
    @graphql.Args() args: WaterAreaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [WaterArea])
  @nestAccessControl.UseRoles({
    resource: "WaterArea",
    action: "read",
    possession: "any",
  })
  async waterAreas(
    @graphql.Args() args: WaterAreaFindManyArgs
  ): Promise<WaterArea[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => WaterArea, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WaterArea",
    action: "read",
    possession: "own",
  })
  async waterArea(
    @graphql.Args() args: WaterAreaFindUniqueArgs
  ): Promise<WaterArea | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => WaterArea)
  @nestAccessControl.UseRoles({
    resource: "WaterArea",
    action: "create",
    possession: "any",
  })
  async createWaterArea(
    @graphql.Args() args: CreateWaterAreaArgs
  ): Promise<WaterArea> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => WaterArea)
  @nestAccessControl.UseRoles({
    resource: "WaterArea",
    action: "update",
    possession: "any",
  })
  async updateWaterArea(
    @graphql.Args() args: UpdateWaterAreaArgs
  ): Promise<WaterArea | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => WaterArea)
  @nestAccessControl.UseRoles({
    resource: "WaterArea",
    action: "delete",
    possession: "any",
  })
  async deleteWaterArea(
    @graphql.Args() args: DeleteWaterAreaArgs
  ): Promise<WaterArea | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
